# Generated by Django 4.0.1 on 2022-01-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=255)),
                ('born_date', models.DateField()),
                ('position', models.CharField(max_length=255)),
                ('active_date', models.DateField()),
                ('deactivated_date', models.DateField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='major.major')),
            ],
        ),
    ]
