# Generated by Django 4.0.1 on 2022-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(default='/media/elon_musk.jpg', upload_to=''),
        ),
    ]
