# Generated by Django 4.0.1 on 2022-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='image',
            field=models.ImageField(default='/media/elon_musk.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image2',
            field=models.ImageField(default='/media/elon_musk.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image3',
            field=models.ImageField(default='/media/elon_musk.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='ImageProperty',
        ),
    ]
